config/routes.rb
Advisor::Application.routes.draw do

  root 'hotels#top'
  resources :hotels do
    get :top, on: :collection
    get :find, on: :collection
  end
  resources :signups,  only: [:new, :create]
  resource  :logins,   only: [:create, :destroy]
  resources :comments, only: :create

  get 'signups' => 'signups#new'
  get 'logins'  => 'logins#new'
  get '*a', :to => 'errors#not_found'

  

end

app/models/address.rb
class Address
  include Mongoid::Document

  field :country, type: String
  field :state,   type: String
  field :sity,    type: String
  field :street,  type: String

  embedded_in :hotel

  validates :country, :state, :sity, :street, presence: true
end

app/models/comment.rb
class Comment
  include Mongoid::Document
  include Mongoid::Timestamps

  field :text, type: String

  embedded_in :hotel
  belongs_to :user

  validates :text, presence: true
end

app/models/hotel.rb
class Hotel
  include Mongoid::Document
  include Mongoid::Timestamps

  field :title,               type: String
  field :star_rating,         type: Integer
  field :breakfast_included,  type: Boolean
  field :room_description,    type: String
  field :price_for_room,      type: Integer

  mount_uploader :photo, PhotoUploader

  embeds_one  :address
  embeds_many :comments
  accepts_nested_attributes_for :address
  belongs_to :user

  validates :title, presence: true
  validates :star_rating, numericality: { greater_than: 0, less_than: 6 }
  validates :price_for_room, presence: true, numericality: { only_integer: true, greater_than: 5 }

  delegate :country, :state, :sity, :street, to: :address

  scope :top, ->(size) { desc(:star_rating).limit(size) }
end

app/models/profile.rb
class Profile
  include Mongoid::Document

  field :first_name, type: String
  field :last_name,  type: String

  embedded_in :user

  validates :first_name, :last_name, presence: true

  def full_name
    first_name + ' ' + last_name
  end
end

app/models/user.rb
class User
  include Mongoid::Document
  include Mongoid::Timestamps

  field :token, type: String
  field :email, type: String
  field :encrypted_password, type: String, encrypted: true

  embeds_one :profile
  accepts_nested_attributes_for :profile
  has_many :hotels


  validates :token, presence: true
  validates :password, presence: true,
                       confirmation: true,
                       length: { in: 6..30 },
                       format: { with: /\A\p{Alnum}+\z/, message: I18n.t('errors.invalid_password') }

  validates :email, presence: true,
                    uniqueness: true,
                    format: { with: /\b[A-Z0-9._%a-z\-]+@(?:[A-Z0-9a-z\-]+\.)+[A-Za-z]{2,4}\z/,
                              message: I18n.t('errors.invalid_email') }

  delegate :full_name, to: :profile
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.where(token: session[:user]).first
  end
  helper_method :current_user

  private

  def find_hotel
    @hotel = Hotel.where(id: params[:id]).first
    (render 'public/record_not_found', layout: false) unless @hotel
  end

  def required_login_user
    unless current_user
      flash[:error] = t('errors.required_user')
      redirect_to :back
    end
  end

  def required_owner_hotel
    unless @hotel.user == current_user
      flash[:error] = t('errors.required_owner')
      redirect_to hotel_path @hotel
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :required_login_user
  before_filter :find_hotel

  def create
    @hotel.comments.create(params[:comment].merge(user_id: current_user.id))
    redirect_to @hotel
  end
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def not_found
    render 'public/404', layout: false
  end
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  COUNT = 5

  before_filter :new_hotel,  only: [:new, :create]
  before_filter :find_hotel, only: [:show, :edit, :update, :destroy]
  before_filter :required_login_user,  only: [:new, :edit, :destroy]
  before_filter :required_owner_hotel, only: [:edit, :update, :destroy]

  def find
    render json: Hotel.only(:title).all
    #render json: []
  end

  def index
    @hotels = Hotel.desc(:created_at)
    render :hotels
  end

  def top
    @hotels = Hotel.top(COUNT)
    render :hotels
  end

  def new
    @hotel.build_address
    render :form, locals: { url: hotels_path, method: 'post' }
  end

  def create
    @hotel.user = current_user
    if @hotel.save
      flash[:success] = t('hotels.create')
      redirect_to @hotel
    else
      render :form, locals: { url: hotels_path, method: 'post' }
    end
  end

  def edit
    render :form, locals: { url: hotel_path, method: 'put' }
  end

  def update
    if @hotel.update_attributes(params[:hotel])
      flash[:success] = t('hotels.update')
      redirect_to @hotel
    else
      render :form, locals: { url: hotel_path, method: 'put' }
    end
  end

  def destroy
    @hotel.remove
    flash[:success] = t('hotels.destroy')
    redirect_to hotels_path
  end

  private

  def new_hotel
    @hotel = Hotel.new(params[:hotel])
  end
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  layout 'application'
  before_filter :find_user, only: :create

  def create
    if @user && @user.password == params[:user][:password]
      session[:user] = @user.token
      redirect_to top_hotels_path
    else
      flash[:error] = t('logins.fail')
      redirect_to logins_path
    end
  end

  def destroy
    reset_session
    redirect_to top_hotels_path
  end

  private

  def find_user
    @user = User.where(email: params[:user][:email]).first
  end
end

app/controllers/signups_controller.rb
class SignupsController < ApplicationController
  layout 'application'

  def new
    if current_user
      flash[:error] = t('signups.already_signup')
      redirect_to top_hotels_path
    end
    @user = User.new
    @user.build_profile
  end

  def create
    @user = User.new(params[:user].merge(token: params[:authenticity_token]))
    if @user.save
      session[:user] = @user.token
      flash[:success] = t('signups.create')
      redirect_to top_hotels_path
    else
      render :new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active(action)
    params[:action] == action ? 'active' : ''
  end

  def signin_out
    if current_user
      link_to t('navbar.log_out'), logins_path, method: 'delete'
    else
      link_to t('navbar.login'), logins_path
    end
  end

  def user_name
    current_user ? current_user.full_name : ''
  end

  def flash_class
    flash[:error] ? 'alert-danger' : 'alert-success'
  end
end

app/views/hotels/form.html.slim
= simple_form_for @hotel, url: url, html: { role: 'form' }, method: method do |f|
  = f.input :title, required: false, input_html: { autocomplete: 'off' }
  = f.input :star_rating, collection: 1..5, input_html: { data: { bind: "value: points" } }, required: false, wrapper: :star_rating, star_wrapper_html: { data: { bind: 'starRating: points' } }
  = f.input :breakfast_included, as: :boolean
  = f.input :room_description, as: :text
  = f.input :price_for_room, required: false, input_html: { autocomplete: 'off' }
  .form-group
    = f.label :photo
    .col-sm-5
      = f.file_field :photo
      span.help-inline= @hotel.errors[:photo].to_sentence
  = f.simple_fields_for :address do |address|
    = address.input :country, required: false, input_html: { autocomplete: 'off' }
    = address.input :state, required: false, input_html: { autocomplete: 'off' }
    = address.input :sity, required: false, input_html: { autocomplete: 'off' }
    = address.input :street, required: false, input_html: { autocomplete: 'off' }
  = f.button :submit

| <script type="text/javascript" src="/assets/star_rating.js"></script>

app/views/hotels/hotels.html.slim
.row
  .col-sm-2= t('hotels.empty_list') if @hotels.blank?
  .col-sm-10= link_to t('hotels.add_hotel'), new_hotel_path, class: 'pull-right'
table class='table hotels-table'
  tbody
    - @hotels.each do |h|
      tr: td: .row
        .col-sm-3= image_tag h.photo.thumb.url
        .col-sm-8.col-sm-offset-1
          .col-sm-12= link_to h.title, hotel_path(h)
          .col-sm-12 data-bind="showStarRating: #{ h.star_rating }"
          .col-sm-3= t('hotels.price')
          .col-sm-9= h.price_for_room
          .col-sm-3= t('hotels.country')
          .col-sm-9= h.country
          .col-sm-3= t('hotels.state')
          .col-sm-9= h.state
          .col-sm-3= t('hotels.sity')
          .col-sm-9= h.sity
          .col-sm-3= t('hotels.street')
          .col-sm-9= h.street

| <script type="text/javascript" src="/assets/star_rating.js"></script>

app/views/hotels/show.html.slim
.row
  .col-sm-2= t('hotels.image')
  .col-sm-3= image_tag @hotel.photo.thumb.url
br
.row
  .col-sm-2= t('hotels.title')
  .col-sm-5= @hotel.title
br
.row
  .col-sm-2= t('hotels.star')
  .col-sm-2 data-bind="showStarRating: #{ @hotel.star_rating }"
br
.row
  .col-sm-2= t('hotels.breakfast')
  .col-sm-5= @hotel.breakfast_included.to_b
br
.row
  .col-sm-2= t('hotels.room')
  .col-sm-5.word-break= @hotel.room_description
br
.row
  .col-sm-2= t('hotels.price')
  .col-sm-5= @hotel.price_for_room
br
.row
  .col-sm-2= t('hotels.country')
  .col-sm-5= @hotel.country
br
.row
  .col-sm-2= t('hotels.state')
  .col-sm-5= @hotel.state
br
.row
  .col-sm-2= t('hotels.sity')
  .col-sm-5= @hotel.sity
br
.row
  .col-sm-2= t('hotels.street')
  .col-sm-5= @hotel.street
br
.row
  .col-sm-2= t('hotels.publisher')
  .col-sm-5= @hotel.user.full_name
br
.row
  .col-sm-2= link_to t('hotels.add_hotel'), new_hotel_path, class: 'btn btn-primary'
  - if @hotel.user == current_user
    .col-sm-2= link_to t('hotels.edit_hotel'), edit_hotel_path(@hotel), class: 'btn btn-primary'
    .col-sm-2= link_to t('hotels.destroy_hotel'), hotel_path(@hotel), method: 'delete', class: 'btn btn-primary'
br
= render file: 'shared/show_comments' if @hotel.comments.present?
= render file: 'shared/comment'

| <script type="text/javascript" src="/assets/star_rating.js"></script>

app/views/layouts/alert.html.slim
div class="alert alert-dismissable text-center #{ flash_class }"
  button.close tupe='button' data-dismiss='alert' aria-hidden='true' &times;
  span= flash[:error] || flash[:success]

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Advisor</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render file: 'layouts/navbar' %>
  <%= render file: 'layouts/alert' if flash.present? %>
  <%= yield %>
</body>
</html>

app/views/layouts/navbar.html.slim
nav class='navbar navbar-default' role='navigation'
  .navbar-header
    button type='button' class='navbar-toggle' data-toggle='collapse' data-target='#hotels-navbar-collapse'
      span class='icon-bar'
      span class='icon-bar'
    .navbar-brand= t('navbar.hotels')
  div class='collapse navbar-collapse' id='hotels-navbar-collapse'
    ul class='nav navbar-nav'
      li class="#{ active('top') }"
        = link_to t('navbar.top'), top_hotels_path
      li class="#{ active('index') }"
        = link_to t('navbar.all'), hotels_path
    ul class='nav navbar-nav navbar-right'
      li
        .navbar-brand= user_name
      li class='dropdown'
        | <a href="#" class="dropdown-toggle" data-toggle="dropdown">#{ t('navbar.action') }<b class="caret"></b></a>
        ul class='dropdown-menu'
          li= signin_out
          li class='divider'
          li= link_to t('navbar.signup'), new_signup_path

app/views/logins/new.html.slim
= simple_form_for :user, url: logins_path do |f|
  = f.input :email, required: false
  = f.input :password, required: false
  = f.button :submit, t('logins.log_in')

app/views/shared/comment.html.slim
= simple_form_for :comment, url: comments_path, method: 'post' do |f|
  = f.hidden_field :id, value: @hotel.id, name: 'id'
  .col-sm-2.none-left-padding= f.button :submit, t('shared.add_comment')
  = f.input :text, as: :text, input_wrapper_html: { class: 'none-left-padding col-sm-7' }, label: false

app/views/shared/show_comments.html.slim
.row
  .col-sm-2: strong= t('hotels.comments')
- @hotel.comments.each do |c|
  br
  .row
    .col-sm-2= c.user.full_name
    .col-sm-10.word-break= c.text
br

app/views/signups/new.html.slim
= simple_form_for @user, url: signups_path do |f|
  = f.simple_fields_for :profile do |p|
    = p.input :first_name, required: false, input_html: {data: {ajax:{href: find_hotels_path}} }
    = p.input :last_name, required: false, input_html: {data: {ajax:{href: find_hotels_path}} }
  = f.input :email, required: false
  = f.input :password, required: false
  = f.input :password_confirmation, required: false
  = f.button :submit, t('signups.sign_up')
javascript:
  initAutocomplete();